backend:
  branch: master
  name: git-gateway
  #base_url: http://netlify-oauth.azurewebsites.net # Path to ext auth provider

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "posts_ca"
    label: "Posts CA"
    folder: "content/posts"
    filter: {field: "language", value: "ca"}    
    create: true
    slug: "{{slug}}.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Autor", name: "author", widget: "string", required: true}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Data", name: "date", widget: "datetime"}
      - label: "Categories"
        name: "categories"
        widget: "select"
        options:
          - { label: "General", value: "general" }
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false      


  - name: "posts_es"
    label: "Posts ES"
    folder: "content/posts"
    filter: {field: "language", value: "es"}    
    create: true
    slug: "{{slug}}.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["es", "ca", "en"]}
      - {label: "Autor", name: "author", widget: "string", required: true}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Data", name: "date", widget: "datetime"}
      - label: "Categories"
        name: "categories"
        widget: "select"
        options:
          - { label: "General", value: "general" }
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false      

  - name: "posts_en"
    label: "Posts EN"
    folder: "content/posts"
    filter: {field: "language", value: "en"}    
    create: true
    slug: "{{slug}}.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Autor", name: "author", widget: "string", required: true}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Data", name: "date", widget: "datetime"}
      - label: "Categories"
        name: "categories"
        widget: "select"
        options:
          - { label: "General", value: "general" }
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false      

  - name: "Pages_CA"
    label: "Pàgines CA"
    folder: "content/pages"
    filter: {field: "language", value: "ca"}    
    create: true
    slug: "{{slug}}.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false      

  - name: "Pages_ES"
    label: "Páginas ES"
    folder: "content/pages"
    filter: {field: "language", value: "es"}    
    create: true
    slug: "{{slug}}.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["es", "ca", "en"]}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false      

  - name: "Pages_EN"
    label: "Pages EN"
    folder: "content/pages"
    filter: {field: "language", value: "en"}    
    create: true
    slug: "{{slug}}.{{language}}"
    fields:
      - {label: "Esborrany", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Idioma", name: "language", widget: "select", options: ["en", "ca", "es"]}
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false      

